### ISSUE TITLE
your plugin on GLPI catalog

### ISSUE THREAD

**Issue by orthagh** [karhel/glpi-karastock#1]
I received your submission on GLPI plugins catalog.

Before i can correctly review it, please fix the following points on your xml file:

- add a good description explaining what's your plugin do
- add screenshots from your plugin (using `fields` plugin one seems a bad idea)
- fill tags, `Another tag` seems a little bit generic
- link a logo, the current placeholder will broke the plugins page design

When done, ping me on this issue and i'll do a new review.

Regards

**Comment by karhel** [comment]
Hi,

Yes, this was a try. 
I fixed the description and XML file, it will be better now

Regards

**Comment by orthagh** [comment]
I validated your plugin.
It should appears in the catalog in less than 1H
