### ISSUE TITLE
No Permision for plugin

### ISSUE THREAD

**Issue by edgarfabiancalderon** [karhel/glpi-karastock#2]
Hi :)

I installed the plugin correctly but when I go to Gestion>stock I get the following message
"You do not have permissions to execute this action

<img width="396" alt="Captura" src="https://user-images.githubusercontent.com/64982932/110469906-35c69580-80a8-11eb-90b2-7f627dacf89b.PNG">

<img width="636" alt="xxs" src="https://user-images.githubusercontent.com/64982932/110470218-9786ff80-80a8-11eb-9ef8-a17053b751b0.PNG">

GLPI VERSION : 9.5.3
Plugin version 1.0

**Comment by mecmav** [comment]
I think you need set permissions to each profile that can see, create, use the plugin... Go to Administration > Profiles > select the desired profile > in the tab "Karastock", active the checkboxes...

**Comment by karhel** [comment]
Hi, indeed, at first install you have to set rights to the profil
