### ISSUE TITLE
Stock - add an item

### ISSUE THREAD

**Issue by LeNorby** [karhel/glpi-karastock#4]
Hello,

How can I add an item to the stock ?
The '+' icon is grayed out ...

Best Regards,
Norbert

**Comment by karhel** [comment]
Hi,

The stock is updated automatically with the orders.
You have to create an Order, with articles, to have a Stock
No directly definition of stock is possible

Regards

**Comment by LeNorby** [comment]
Hi,
Ok thanks.
And if we need to update a Stock of items, the only solution is to modify the order and delete an article ?

Best regards,
Norbert
