### ISSUE TITLE
Possible to create new "Item Type" ? 

### ISSUE THREAD

**Issue by kbengmy** [karhel/glpi-karastock#6]
Hi, I'm new to GLPI and I'm exploring the possibility of using Karastock in managing stationery items. 

Is it possible to create new "Item Type" ? 

<img src="https://i.ibb.co/fCyRz88/Karastock-Item-Type.png" alt="Karastock-Item-Type" border="0">

Thanks.

**Comment by karhel** [comment]
Hi, that's not so simple, I added "Other" on the dropdown but all others came from the GLPI Core list
Some new features will use this GLPI Core Classes

**Comment by karhel** [comment]
Hi, This feature is based on the GLPI Core Classes and allow you to link order item to devices (computer, network devices...) so that's not possible
